### ISSUE TITLE
Messenger is throwing an exception because the collection of subscribers has been modified.

### ISSUE THREAD

**Issue by smithmx** [dolittle/Bifrost#658]
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Bifrost.Messaging.Messenger.Publish[T](T content)
   at Drofus.Components.UI.Views.SystemComponentsViewModel.Refresh(Object sender)
   --- End of inner exception stack trace ---
   at mscorlib!0x06001205!System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Bifrost.Execution.WeakDelegate.DynamicInvoke(Object[] arguments)
   at Bifrost.Messaging.Messenger.Publish[T](T content)
   at Nosyko.Drofus.Revit.DrofusRevitPlugin.ProcessTask(UIApplication uiapp, Queue`1 tasks)

Instead of 

foreach (var subscriber in _subscribers[type])

we should do

foreach (var subscriber in _subscribers[type].ToList())

**Comment by einari** [comment]
Would it be an option to make the _subscribers a ConcurrentBag instead.

**Comment by smithmx** [comment]
Yeah, that's fine as well.  It might even be better as we are more likely removing subscriptions while iterating than adding them.
